src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.dashboard.views import AdminDashboardView, admin_dashboard_statistics_view
from apps.films.views import AdminFilmsView, AdminCreateFilmView, AdminUpdateFilmView, AdminDeleteFilmImageView, \
    AdminDeleteFilmView, BillboardView, SoonView, FilmView, film_search_view
from apps.users.views import AdminLoginView, AdminLogoutView, AdminUsersView, AdminUsersDatatableView, \
    AdminUpdateUserView, AdminDeleteUserView, LoginView, RegisterView, LogoutView, ProfileView
from apps.banners.views import AdminBannersView, AdminBackgroundSettingsView, AdminTopBannersView, \
    AdminAdvertisementBannersView, AdminDeleteBackgroundView
from apps.cinemas.views import AdminCinemasView, AdminCreateCinemaView, AdminUpdateCinemaView, \
    AdminDeleteCinemaBannerView, AdminDeleteCinemaLogoView, AdminDeleteCinemaView, CinemaListView, CinemaDetailView
from apps.halls.views import AdminHallsDataTableView, AdminCreateHallView, AdminUpdateHallView, \
    AdminDeleteHallSchemeView, AdminDeleteHallBannerView, AdminDeleteHallView, HallDetailView
from apps.news.views import AdminNewsView, AdminCreateNewsView, AdminUpdateNewsView, AdminDeleteNewsImageView, \
    AdminNewsDataTableView, AdminDeleteNewsView, NewsListView, NewsDetailView
from apps.promotions.views import AdminPromotionsView, AdminPromotionsDataTableView, AdminCreatePromotionView, \
    AdminUpdatePromotionView, AdminDeletePromotionView, AdminDeletePromotionImageView, PromotionsListView, \
    PromotionsDetailView
from apps.pages.views import AdminPagesView, AdminMainPageView, AdminCreatePageView, AdminUpdatePageView, \
    AdminDeletePageView, AdminDeletePageImageView, AdminContactsView, AdminDeleteContactLogoView, MainPageView, \
    ContactsPageView, PageView
from apps.mailing.views import AdminMailingView, AdminUploadTemplateView, AdminDeleteTemplateView, \
    AdminMailingDatatableView, admin_send_emails_view
from apps.schedule.views import ScheduleView, schedule_cinemas_view, schedule_dates_view, schedule_films_view, \
    schedule_halls_view, schedule_sessions_view, ScheduleDetailView, tickets_view
from core.views import change_language_view

adminlte = [
    path("authentication/login/", AdminLoginView.as_view(), name="adminlte_authentication_login"),
    path("authentication/logout/", AdminLogoutView.as_view(), name="adminlte_authentication_logout"),
    path("dashboard/", AdminDashboardView.as_view(), name="adminlte_dashboard"),
    path("dashboard/statistics/", admin_dashboard_statistics_view, name="adminlte_dashboard_statistics"),
    path("banners/", AdminBannersView.as_view(), name="adminlte_banners"),
    path("banners/background-settings/", AdminBackgroundSettingsView.as_view(),
         name="adminlte_banners_background_settings"),
    path("banners/background-settings/background/delete/", AdminDeleteBackgroundView.as_view(),
         name="adminlte_banners_background_settings_banner_delete"),
    path("banners/top-banners/", AdminTopBannersView.as_view(), name="adminlte_banners_top_banners_settings"),
    path("banners/advertisement-banners/", AdminAdvertisementBannersView.as_view(),
         name="adminlte_banners_advertisement_banners_settings"),
    path("films/", AdminFilmsView.as_view(), name="adminlte_films"),
    path("films/create/", AdminCreateFilmView.as_view(), name="adminlte_films_create_film"),
    path("films/<int:film_id>/update/", AdminUpdateFilmView.as_view(), name="adminlte_films_update_film"),
    path("films/<int:film_id>/delete/", AdminDeleteFilmView.as_view(), name="adminlte_films_delete_film"),
    path("films/<int:film_id>/image/", AdminDeleteFilmImageView.as_view(), name="adminlte_films_delete_film_image"),
    path("cinemas/", AdminCinemasView.as_view(), name="adminlte_cinemas"),
    path("cinemas/create/", AdminCreateCinemaView.as_view(), name="adminlte_cinemas_create_cinema"),
    path("cinemas/<int:cinema_id>/update/", AdminUpdateCinemaView.as_view(), name="adminlte_cinemas_update_cinema"),
    path("cinemas/<int:cinema_id>/delete/", AdminDeleteCinemaView.as_view(), name="adminlte_cinemas_delete_cinema"),
    path("cinemas/<int:cinema_id>/banner/", AdminDeleteCinemaBannerView.as_view(),
         name="adminlte_cinema_delete_cinema_banner"),
    path("cinemas/<int:cinema_id>/logo/", AdminDeleteCinemaLogoView.as_view(),
         name="adminlte_cinema_delete_cinema_logo"),
    path("cinemas/<int:cinema_id>/halls/create/", AdminCreateHallView.as_view(), name="adminlte_halls_create_hall"),
    path("halls/<int:hall_id>/update/", AdminUpdateHallView.as_view(),
         name="adminlte_halls_update_hall"),
    path("halls/<int:hall_id>/delete/", AdminDeleteHallView.as_view(),
         name="adminlte_halls_delete_hall"),
    path("halls/datatable/", AdminHallsDataTableView.as_view(), name="adminlte_halls_datatable"),
    path("halls/<int:hall_id>/banner/", AdminDeleteHallBannerView.as_view(), name="adminlte_halls_delete_hall_banner"),
    path("halls/<int:hall_id>/scheme/", AdminDeleteHallSchemeView.as_view(), name="adminlte_halls_delete_hall_scheme"),
    path("news/", AdminNewsView.as_view(), name="adminlte_news"),
    path("news/datatable/", AdminNewsDataTableView.as_view(), name="adminlte_news_datatable"),
    path("news/create/", AdminCreateNewsView.as_view(), name="adminlte_news_create_news"),
    path("news/<int:news_id>/update/", AdminUpdateNewsView.as_view(), name="adminlte_news_update_news"),
    path("news/<int:news_id>/image/", AdminDeleteNewsImageView.as_view(),
         name="adminlte_news_delete_news_image"),
    path("news/<int:news_id>/delete/", AdminDeleteNewsView.as_view(),
         name="adminlte_news_delete_news"),
    path("promotions/", AdminPromotionsView.as_view(), name="adminlte_promotions"),
    path("promotions/datatable/", AdminPromotionsDataTableView.as_view(), name="adminlte_promotions_datatable"),
    path("promotions/create/", AdminCreatePromotionView.as_view(), name="adminlte_promotions_create_promotion"),
    path("promotions/<int:promotion_id>/update/", AdminUpdatePromotionView.as_view(),
         name="adminlte_promotions_update_promotion"),
    path("promotions/<int:promotion_id>/image/", AdminDeletePromotionImageView.as_view(),
         name="adminlte_promotions_delete_promotion_image"),
    path("promotions/<int:promotion_id>/delete/", AdminDeletePromotionView.as_view(),
         name="adminlte_promotions_delete_promotion"),
    path("pages/", AdminPagesView.as_view(), name="adminlte_pages"),
    path("pages/main/", AdminMainPageView.as_view(), name="adminlte_pages_main_page"),
    path("pages/create/", AdminCreatePageView.as_view(), name="adminlte_pages_create_page"),
    path("pages/<int:page_id>/update/", AdminUpdatePageView.as_view(), name="adminlte_pages_update_page"),
    path("pages/<int:page_id>/delete/", AdminDeletePageView.as_view(), name="adminlte_pages_delete_page"),
    path("pages/<int:page_id>/image/", AdminDeletePageImageView.as_view(), name="adminlte_pages_delete_page_image"),
    path("pages/contacts/", AdminContactsView.as_view(), name="adminlte_pages_contacts"),
    path("pages/contacts/<int:contact_id>/logo/", AdminDeleteContactLogoView.as_view(),
         name="adminlte_pages_contacts_delete_contact_logo"),
    path("users/", AdminUsersView.as_view(), name="adminlte_users"),
    path("users/datatable/", AdminUsersDatatableView.as_view(), name="adminlte_users_datatable"),
    path("users/<int:user_id>/update/", AdminUpdateUserView.as_view(), name="adminlte_users_update_user"),
    path("users/<int:user_id>/delete/", AdminDeleteUserView.as_view(), name="adminlte_users_delete_user"),
    path("mailing/", AdminMailingView.as_view(), name="adminlte_mailing"),
    path("mailing/upload/", AdminUploadTemplateView.as_view(), name="adminlte_mailing_upload_template"),
    path("mailing/templates/<int:template_id>/delete/", AdminDeleteTemplateView.as_view(),
         name="adminlte_mailing_delete_template"),
    path("mailing/datatable/", AdminMailingDatatableView.as_view(), name="adminlte_mailing_datatable"),
    path("mailing/send/", admin_send_emails_view, name="adminlte_mailing_send_email")
]

site = [
    path('change-language/', change_language_view, name='site_change_language'),
    path("authentication/register/", RegisterView.as_view(), name="site_authentication_register"),
    path("authentication/login/", LoginView.as_view(), name="site_authentication_login"),
    path("authentication/logout/", LogoutView.as_view(), name="site_authentication_logout"),
    path("main/", MainPageView.as_view(), name="site_main"),
    path("contacts/", ContactsPageView.as_view(), name="site_contacts"),
    path("profile/", ProfileView.as_view(), name="site_profile"),
    path("news/", NewsListView.as_view(), name="site_news"),
    path("news/<int:pk>/", NewsDetailView.as_view(), name="site_news_detail"),
    path("promotions/", PromotionsListView.as_view(), name="site_promotions"),
    path("promotions/<int:pk>/", PromotionsDetailView.as_view(), name="site_promotions_detail"),
    path("pages/<int:pk>/", PageView.as_view(), name="site_pages_detail"),
    path("cinemas/", CinemaListView.as_view(), name="site_cinemas"),
    path("cinemas/<int:pk>/", CinemaDetailView.as_view(), name="site_cinemas_detail"),
    path("halls/<int:pk>/", HallDetailView.as_view(), name="site_halls_detail"),
    path("schedule/", ScheduleView.as_view(), name="site_schedule"),
    path("schedule/<int:pk>/", ScheduleDetailView.as_view(), name="site_schedule_detail"),
    path("schedule/<int:session_id>/tickets/", tickets_view, name="site_schedule_tickets"),
    path("schedule/cinemas/", schedule_cinemas_view, name="site_schedule_cinemas"),
    path("schedule/dates/", schedule_dates_view, name="site_schedule_showtime"),
    path("schedule/films/", schedule_films_view, name="site_schedule_films"),

src/apps/promotions/models.py
import urllib.parse

from django.db import models

from core.utilities.models import SEOModel, get_upload_path


class Promotions(SEOModel):
    is_active = models.BooleanField(default=True)
    publication_date = models.DateField()
    name_uk = models.CharField()
    name_en = models.CharField()
    description_uk = models.TextField()
    description_en = models.TextField()
    image = models.ImageField(upload_to=get_upload_path)
    video_url = models.URLField()

    @property
    def video_id(self):
        params = urllib.parse.parse_qs(urllib.parse.urlparse(self.video_url).query)
        return params['v'][0]


class PromotionsImage(models.Model):
    image = models.ImageField(upload_to=get_upload_path)
    promotion = models.ForeignKey(Promotions, on_delete=models.CASCADE)

src/apps/promotions/views.py
from ajax_datatable import AjaxDatatableView
from django.contrib import messages
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View, ListView, DetailView

from apps.promotions.forms import PromotionsForm, PromotionsImageFormSet
from apps.promotions.models import Promotions, PromotionsImage
from core.utilities.guards import admin_only


@admin_only
class AdminPromotionsView(TemplateView):
    template_name = 'adminlte/panel/promotions/promotions_table.html'


class AdminPromotionsDataTableView(AjaxDatatableView):
    model = Promotions
    title = 'Promotions'
    initial_order = [["id", "asc"], ]
    length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, 'all']]
    search_values_separator = '+'

    column_defs = [
        {'name': 'id', 'title': 'ID', 'visible': True, },
        {'name': 'name_en', 'title': 'Name', 'visible': True, },
        {'name': 'publication_date', 'title': 'Publication Date', 'visible': True, },
        {'name': 'is_active', 'title': 'Status', 'visible': True, },
        {'name': 'update_or_delete',
         'title': 'Update Or Delete',
         'placeholder': True, 'visible': True,
         'searchable': False,
         'orderable': False, },
    ]

    def customize_row(self, row, obj):
        row['update_or_delete'] = f"""
        <div class="d-flex flex-nowrap">
          <a
          href='{reverse('adminlte_promotions_update_promotion', kwargs={'promotion_id': obj.id})}'
          class="btn btn-primary text-nowrap mr-2">
            <i class="fa fa-pen" aria-hidden="true"></i>
            Update
          </a>
          <a
            href='{reverse('adminlte_promotions_delete_promotion', kwargs={'promotion_id': obj.id})}'
            class="btn btn-info btn-danger text-nowrap"
            data-toggle="modal"
            data-target="#confirmationModal"
          >
            <i class="fa fa-trash" aria-hidden="true"></i>
            Delete
          </a>
        </div>
        """

        row['is_active'] = '<p>Enabled</p>' if obj.is_active else '<p>Disabled</p>'


@admin_only
class AdminCreatePromotionView(TemplateView):
    template_name = 'adminlte/panel/promotions/promotion.html'

    def get(self, request, *args, **kwargs):
        form = PromotionsForm()
        formset = PromotionsImageFormSet()

        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def post(self, request, *args, **kwargs):
        form = PromotionsForm(request.POST, request.FILES)
        formset = PromotionsImageFormSet(request.POST, request.FILES)

        if form.is_valid() and formset.is_valid():
            promotion = form.save(commit=True)
            images = formset.save(commit=False)

            for image in images:
                image.promotion = promotion
                image.save()

            messages.success(request, "Promotion was created successfully")
            return redirect('adminlte_promotions')

        messages.error(request, "Some errors occurred while creating promotion")
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


@admin_only
class AdminUpdatePromotionView(TemplateView):
    template_name = "adminlte/panel/promotions/promotion.html"

    def get(self, request: HttpRequest, *args, **kwargs):
        promotion_id: int = kwargs.get('promotion_id')
        promotion = Promotions.objects.get(pk=promotion_id)
        form = PromotionsForm(instance=promotion)
        formset = PromotionsImageFormSet(instance=promotion)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request: HttpRequest, *args, **kwargs):
        promotion_id: int = kwargs.get('promotion_id')
        promotion = Promotions.objects.get(pk=promotion_id)
        form = PromotionsForm(request.POST, request.FILES, instance=promotion)
        formset = PromotionsImageFormSet(request.POST, request.FILES, instance=promotion)

        if form.is_valid() and formset.is_valid():
            form.save(commit=True)
            formset.save(commit=True)

            messages.success(request, "Promotion was updated successfully")
            return redirect('adminlte_promotions')

        messages.error(request, "Some errors occurred while updating promotion")
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


@method_decorator(csrf_exempt, name='dispatch')
@admin_only
class AdminDeletePromotionImageView(View):
    @staticmethod
    def delete(request: HttpRequest, *args, **kwargs):
        promotion_id: int = kwargs.get('promotion_id')
        Promotions.objects.get(pk=promotion_id).image.delete()
        return JsonResponse({"status": 202})


@admin_only
class AdminDeletePromotionView(View):
    @staticmethod
    def post(request: HttpRequest, *args, **kwargs):
        promotion_id: int = kwargs.get('promotion_id')
        Promotions.objects.get(pk=promotion_id).delete()
        messages.success(request, "Promotion was deleted successfully")
        return redirect("adminlte_promotions")


class PromotionsListView(ListView):
    template_name = 'site/promotions/promotions_list.html'
    paginate_by = 10
    queryset = Promotions.objects.filter(is_active=True)


class PromotionsDetailView(DetailView):
    template_name = 'site/promotions/promotions_detail.html'
    model = Promotions
    context_object_name = 'promotion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['images'] = PromotionsImage.objects.filter(promotion=self.object)
        return context

templates/adminlte/panel/promotions/promotion.html
{% extends "adminlte/panel/base.html" %}
{% load static %}
{% block title %}
  Promotion
{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'custom/css/responsive-inputs.css' %}">
  <link rel="stylesheet" href="{% static 'custom/css/preview.css' %}">
  <link rel="stylesheet" href="{% static 'custom/css/delete-corner-button.css' %}">
  <link rel="stylesheet" href="{% static 'custom/css/horizontal-formset.css' %}">
  <link rel="stylesheet" href="{% static 'custom/css/skeleton.css' %}">
{% endblock head %}
{% block content %}
  <div class="card">
    <div class="card-header p-2">
      Promotion
    </div>
    <div class="card-body p-2">
      <form method="post" enctype="multipart/form-data">
        <ul class="nav nav-tabs mb-2">
          <li class="nav-item ml-auto">
            <a class="nav-link active" id="tab-en">English</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="tab-uk">Українська</a>
          </li>
        </ul>
        {% csrf_token %}
        {{ form.id }}
        <!--General Information-->
        <h5 class="ml-2">General information</h5>
        <div class="switch-date mb-2">
          <!--Switch-->
          <div class="custom-control custom-switch">
            {{ form.is_active }}
            <label class="custom-control-label form-check-label mb-1"
                   for="id_is_active">
              Enabled / Disabled
            </label>
          </div>
          <!--Date picker-->
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
            </div>
            {{ form.publication_date }}
          </div>
        </div>
        <div class="input-group mb-2 en">
          <div class="input-group-prepend">
            <span class="input-group-text">Promotion name in English</span>
          </div>
          {{ form.name_en }}
        </div>
        <div class="input-group mb-2 en">
          <div class="input-group-prepend">
            <span class="input-group-text">Promotion description in English</span>
          </div>
          {{ form.description_en }}
        </div>
        <div class="input-group mb-2 uk">
          <div class="input-group-prepend">
            <span class="input-group-text">Promotion name in Ukrainian</span>
          </div>
          {{ form.name_uk }}
        </div>
        <div class="input-group mb-2 uk">
          <div class="input-group-prepend">
            <span class="input-group-text">Promotion description in Ukrainian</span>
          </div>
          {{ form.description_uk }}
        </div>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Video URL</span>
          </div>
          {{ form.video_url }}
        </div>
        <!--Main Image-->
        <h5 class="ml-2">Main Image</h5>
        {% if form.instance.image %}
          <div class="preview-banner">
            <img src="{{ form.instance.image.url }}" alt="preview">
          </div>
        {% else %}
          <div class="preview-banner skeleton"></div>
        {% endif %}
        <div class="input-group mb-3">
          <div class="custom-file">
            <label class="custom-file-label" for=for="{{ form.image.auto_id }}">
              Choose file
            </label>
            {{ form.image }}
          </div>
          <button
            type="button"
            class="btn btn-primary btn-danger ml-2{% if not form.instance.image %} disabled {% endif %}"
            id="delete-promotion-main-image-button">
            <i class="fa fa-trash" aria-hidden="true"></i>
            Delete
          </button>
        </div>
        <!--Image Gallery-->
        <h5 class="ml-2 mt-2">Image gallery</h5>
        <p class="ml-2 mb-0">Size: 1000 × 190</p>
        <div class="scrolling-wrapper">
          <div class="mt-3">
            {{ formset.management_form }}
            {% for form in formset %}
              {% for hidden in form.hidden_fields %}
                {{ hidden }}
              {% endfor %}
              <div class="card border">
                <div class="card-body p-2">
                  {% if form.instance.image %}
                    <div class="preview-formset">
                      <img src="{{ form.instance.image.url }}" alt="preview">
                    </div>
                  {% else %}
                    <div class="preview-formset skeleton">
                    </div>
                  {% endif %}
                  <div class="input-group mb-3">
                    <div class="custom-file">
                      <label class="custom-file-label">Choose file</label>
                      {{ form.image }}
                    </div>
                  </div>
                </div>
                <div style="display: none">
                  {{ form.DELETE }}
                </div>
                <button type="button"
                        class="btn btn-sm btn-primary btn-danger btn-circle delete-corner-button delete-promotion-image-button">
                  <i class="fa fa-times" aria-hidden="true"></i>
                </button>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="d-flex justify-content-end">
          <button type="button"
                  class="btn btn-primary btn-info"
                  id="add-promotion-image-button">
            <i class="fa fa-plus-circle" aria-hidden="true"></i>
            Add form
          </button>
        </div>
        <!--SEO Block-->
        <h5 class="ml-2 mb-1 mt-3">SEO Block</h5>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">URL</span>
          </div>
          {{ form.seo_url }}
        </div>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Title</span>
          </div>
          {{ form.seo_title }}
        </div>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Keywords</span>
          </div>
          {{ form.seo_keywords }}
        </div>
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <span class="input-group-text">Description</span>
          </div>
          {{ form.seo_description }}
        </div>
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-success mr-2">
            <i class="fa fa-bookmark" aria-hidden="true"></i>
            Save
          </button>
          <button type="button" class="btn btn-info" id="reset-form-button">
            <i class="fa fa fa-minus" aria-hidden="true"></i>
            Reset
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}
{% block script %}
  <script>
    $(function () {
      $('#id_date-picker').inputmask('dd/mm/yyyy', {'placeholder': 'dd/mm/yyyy'});
      $('[data-mask]').inputmask();
    });

    const $wrappers = $('.scrolling-wrapper');
    const $emptyPromotionImageForm = $wrappers.eq(0).find('.mt-3 .card:last-child').clone(true);

    $wrappers.each(function () {
      let isDown = false;
      let startX;
      let startY;
      let scrollLeft;
      let scrollTop;

      $(this).on('mousedown', function (e) {
        isDown = true;
        startX = e.pageX;
        startY = e.pageY;
        scrollLeft = $(this).scrollLeft();
        scrollTop = $(this).scrollTop();
        $(this).css('cursor', 'grabbing');
      });

      $(this).on('mouseleave mouseup', function () {
        isDown = false;
        $(this).css('cursor', 'grab');
      })

      const $wrapper = this;

      $(document).on('mousemove', function (e) {
        if (!isDown) return;
        e.preventDefault();
        const x = e.pageX - $wrapper.offsetLeft;
        const y = e.pageY - $wrapper.offsetTop;
        const walkX = x - startX;
        const walkY = y - startY;
        $wrapper.scrollLeft = scrollLeft - walkX;
        $wrapper.scrollTop = scrollTop - walkY;
      });
    })


    $('#add-promotion-image-button').click(function () {
      const $totalForms = $('#id_promotionsimage_set-TOTAL_FORMS');
      const count = parseInt($totalForms.val());

      const $promotionImageFormMarkup = $emptyPromotionImageForm.prop('outerHTML');
      const regex = /promotionsimage_set-(\d+)-/g;
      const $compiledPromotionImageForm = $promotionImageFormMarkup.replace(regex, `promotionsimage_set-${count}-`);

      $wrappers.eq(0).find('.mt-3').append($compiledPromotionImageForm);

      $totalForms.attr('value', count + 1);

      $wrappers.eq(0).animate({
        scrollLeft: $wrappers.eq(0).prop('scrollWidth')
      }, 500);
    });

    $(document).on('click', '.delete-promotion-image-button', function () {
      const $card = $(this).closest('.card');
      $card.find('input[type="checkbox"]').prop('checked', true);
      $card.hide();
    })

    $('.uk').hide();

    $('.card-body .nav-link').click(function () {
      const clickedTabId = $(this).attr('id');

      $('.card-body .nav-link').removeClass('active');
      $(this).addClass('active');

      if (clickedTabId === 'tab-en') {
        $('.uk').hide();
        $('.en').show();
      } else {
        $('.uk').show();
        $('.en').hide();
      }
    });

    $("input[type='text'], input[type='url'], textarea").each(function () {
      $(this).attr('data-initial', $(this).val());
    });

    $("#reset-form-button").click(function (e) {
      e.preventDefault();

      $("input[type='text'], input[type='url'], textarea").each(function () {
        const initial = $(this).attr('data-initial');
        $(this).val(initial);
      });
    })

    $(document).on('change', 'input:file', function (e) {
      $(this).prev().html($(this).val().split('\\').pop());

      const image = e.target.files[0];
      const src = URL.createObjectURL(image);

      const $preview = $(this).parent().parent().prev();

      const className = $($preview)
        .attr('class')
        .split(/\s+/)
        .find(className => className.startsWith('preview'));

      $preview.remove();

      const $previewContainer = $(`<div class=${className}>`);
      $previewContainer.insertBefore($(this).closest('.input-group'));

      const $image = $(`<img src=${src} alt="preview">`);
      $previewContainer.append($image);
    });

    {% if form.instance.id %}
      $('#delete-promotion-main-image-button').click(function () {
          const $button = $(this);
          $.ajax({
            url: "{% url 'adminlte_promotions_delete_promotion_image' promotion_id=form.instance.id %}",
            method: "DELETE",
            success: function (data) {
              if (data.status === 202) {
                toastr.success("Promotion image was deleted successfully");

                const $preview = $button.parent().prev();
                $preview.remove();
                const $previewContainer = $(`<div></div>`);
                $previewContainer.addClass('preview-banner skeleton')
                $previewContainer.insertBefore($($button).closest('.input-group'));

                $("#id_image").prop('required', true);
                $button.addClass("disabled")
              }
            }
          })
        }
      )
    {% endif %}
  </script>
{% endblock script %}